### PR TITLE
PEP 570: Restructure sections as recommended by PEP 1

### PR DESCRIPTION
**Pull request by ericvw**
Organize PEP 570 according to the recommended ordering of sections
    defined in PEP 1.  This presents the proposal in a more organized
    fashion.

Specifically, the proposal reads in a more organized top-down fashion,
    an explicit mention of API authors and callers are distinguished,
    "parameters" and "arguments" are used correctly, and other grammatical
    corrections and slight rewording.

While the diff looks drastic, the core content of the originally written
    PEP remains in tact.

---

@gvanrossum, @pablogsal and @mariocj89 asked me to help out with PEP 570, being a native English speaker.

When reading through the PEP, I have conferred with Pablo and Mario if I could take a stab on restructuring the ordering to match more closely with the outlined sections from PEP 1 (e.g., Abstract, Motivation, Rationale, Specification, etc).  I have already completed the restructuring, made the problems & benefits for API authors and callers explicit, and fixed-up usage of “parameter” vs “argument” in the text.  Overall, I think this restructure makes PEP 570 more compelling the sections logically flow when reading from one section to the next.

I understand you are now [looking only for minor edits and clarification for the PEP at this point](https://discuss.python.org/t/pep-570-python-positional-only-parameters/1078/138) and may find this restructure disruptive.  However, would you be amenable to this change that also includes grammatical edits and slight rewording within the core content?

I've reviewed this change with @pablogsal and @@mariocj89 already, but wanted to run this by you.  Thanks!

### CODE REVIEW

**Comment by gvanrossum** [comment]
When @pablogsal agrees to this diff he should probably just merge it into his repo and turn it into a diff for the upstream peps repo. (Honestly why didn't you submit this as a PR there?)

**Comment by ericvw** [comment]
> (Honestly why didn't you submit this as a PR there?)

@pablogsal asked me to submit the PR to his fork to inquire if this change would be too disruptive.

@pablogsal let me know how you would like to proceed.  I am happy to leave the PR to your fork or I can submit it to the peps repository.

**Comment by pablogsal** [comment]
@ericvw As the PR that I had has been merged, at this point I think the best is a PR directly to the peps repo.

**Comment by ericvw** [comment]
Sounds great.  I am doing a final pass for minor grammatical edits and will submit a PR directly to the peps repository.

**Pull request closed without merging**
